# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_teacher_year'),
        ('courses', '0006_course_is_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='\u8bfe\u7a0b\u8bb2\u5e08'),
        ),
    ]
