# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20181118_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourse',
            options={'verbose_name': '\u7528\u6237\u8bfe\u7a0b', 'verbose_name_plural': '\u7528\u6237\u8bfe\u7a0b'},
        ),
    ]
