# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='year',
            field=models.IntegerField(default=0, verbose_name='\u5e74\u9f84'),
        ),
    ]
